**1. Create a 5X2 integer array from a range between 100 to
200 such that the difference between each element is 10.**

In [1]:
import numpy as np

ar = np.arange(100, 200, 10)
ar = ar.reshape(5, 2)
ar

array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

**2. Write a NumPy program to create a 3x3x3 array filled
with arbitrary values and find the minimum and maximum
values.**

In [ ]:
x = np.random.random((3, 3, 3))
print("An array of 3x3x3:\n",x,"\n")
print("The minimum value is: ",x.min())
print("The maximum value is: ",x.max())

An array of 3x3x3:
 [[[0.20741628 0.52259066 0.56855003]
  [0.22537112 0.02095465 0.27247042]
  [0.09314534 0.38009788 0.23270571]]

 [[0.0109948  0.56328114 0.81900748]
  [0.76526211 0.38670471 0.9756617 ]
  [0.24903584 0.36827808 0.02418595]]

 [[0.0721782  0.72779779 0.98439767]
  [0.83023593 0.28946173 0.07292808]
  [0.45758933 0.88910838 0.38884385]]] 

The minimum value is:  0.010994799067693406
The maximum value is:  0.984397666477375


**3. Write a NumPy program to create a 5x5 zero matrix
with elements on the main diagonal equal to 1, 2, 3, 4, 5.**

In [15]:
x = np.diag([1, 2, 3, 4, 5])
x

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

**4. Given an array**

**arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])**

**i) Extract all odd numbers from arr**

**ii) Replace all odd numbers in arr with -1**

In [25]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print("Given array:",arr)

## i) Extract all odd numbers from arr
a = arr[arr%2 == 1]
print("Extracting all odd numbers from above array: ",a)

## ii) Replace all odd numbers in arr with -1
arr[arr%2 == 1] = -1
print("Replacing all odd numbers to -1 from above array:",arr)

Given array: [0 1 2 3 4 5 6 7 8 9]
Extracting all odd numbers from above array:  [1 3 5 7 9]
Replacing all odd numbers to -1 from above array: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


**5. Write a NumPy program to create a 3x3 identity matrix,
i.e. diagonal elements are 1,the rest are 0.**

In [26]:
x = np.diag([1, 1, 1])
x

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

**6. Write a NumPy program to convert an array to a float
type.**

In [28]:
b = [1, 2, 3, 4, 5, 6, 7]
print("The original array:",b)
print("Converting the array to float type.............")
x = np.asfarray(b)
print("The float type array:",x)

The original array: [1, 2, 3, 4, 5, 6, 7]
Converting the array to float type.............
The float type array: [1. 2. 3. 4. 5. 6. 7.]


**7. Write a NumPy program to generate five random
numbers from the normal distribution.**

In [31]:
x = np.random.normal(size=5)
x

array([-0.59351826,  0.78086317,  0.49359356, -0.2627222 , -0.39819618])

**8. Following is the input NumPy array delete column two
and insert following new column in its place.**

**sampleArray=numpy.array([[34,43,73],[82,22,12],[53,94,
66]])**

**newColumn = numpy.array([[10,10,10]])**

In [59]:
sampleArray=np.array([[34,43,73],[82,22,12],[53,94, 66]])
print("The original array:\n",sampleArray)

##deleting column two
z = np.delete(sampleArray,1,1)
print("Deleting column two from above array:\n",z)

##adding new elements to column two
newColumn = np.array([[10,10,10]])
y = np.insert(z, 1, newColumn, axis=1)  ## adding values before index 1
print("Adding new elements to above array as second column:\n",y)

The original array:
 [[34 43 73]
 [82 22 12]
 [53 94 66]]
Deleting column two from above array:
 [[34 73]
 [82 12]
 [53 66]]
Adding new elements to above array as second column:
 [[34 10 73]
 [82 10 12]
 [53 10 66]]


**9. Write a NumPy program to compute the multiplication
of two given matrices.**

In [61]:
a = [[1, 2], [2, 4]]
b = [[2, 1], [4, 5]]
print(a)
print(b)

mul = np.dot(a, b)
print("Multiplying the above two matrices \n",mul)

[[1, 2], [2, 4]]
[[2, 1], [4, 5]]
Multiplying the above two matrices 
 [[10 11]
 [20 22]]


**10. Write a NumPy program to create a random vector of
size 10 and sort it.**

In [67]:
x = np.random.random(10)
print("The original array:\n",x)
print("\n")
x.sort()
print("The sorted array:\n",x)

The original array:
 [0.03827824 0.69205032 0.32393982 0.14483215 0.01903044 0.69433647
 0.29353185 0.85700492 0.41968123 0.48205207]


The sorted array:
 [0.01903044 0.03827824 0.14483215 0.29353185 0.32393982 0.41968123
 0.48205207 0.69205032 0.69433647 0.85700492]


**11. Write a NumPy program to compute the covariance
matrix of two arrays.**

In [70]:
a = np.array([0, 1, 2])
b = np.array([4, 5, 6])
print(a)
print(b)

print("The covariance of above two matrices:\n",np.cov(a,b))

[0 1 2]
[4 5 6]
The covariance of above two matrices:
 [[1. 1.]
 [1. 1.]]


**12.Create a 4X2 integer array and Prints its :**

**i)The shape of an array.**

**ii) Array dimensions.**

**iii) The Length of each element of the array in bytes**

In [78]:
a = np.arange(8).reshape(4,2)
print("The 4x2 array:\n",a)

## i)The shape of an array.
print("The shape of the array:\n",a.shape)

## ii) Array dimensions.
print("Array dimensions:\n",a.size)

## iii) The Length of each element of the array in bytes
print("The Length of each element of the array in bytes:\n",a.nbytes)

The 4x2 array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]]
The shape of the array:
 (4, 2)
Array dimensions:
 8
The Length of each element of the array in bytes:
 64


**13. Write a NumPy program to concatenate element-wise
two arrays of string.**

In [8]:
a1 = np.array(['Hi', 'Good'])
a2 = np.array([' All', ' Morning'])
print(a1)
print(a2)

new = np.char.add(a1, a2)
print("The result of concatenation:\n",new)

['Hi' 'Good']
[' All' ' Morning']
The result of concatenation:
 ['Hi All' 'Good Morning']


**14. Write a NumPy program to capitalize the first letter,
lowercase, uppercase, swapcase, title-case of all the
elements of a given array.**

In [21]:
a = np.array(['APple', 'oranGE', 'cHErry', 'maNGo'])
print("The given array:\n",a)

cap = np.char.capitalize(a)
low = np.char.lower(a)
up = np.char.upper(a)
swap = np.char.swapcase(a)
tc = np.char.title(a)

print("Capitalize: ", cap)
print("Lowercase: ", low)
print("Uppercase: ", up)
print("Swapcase: ", swap)
print("Titlecase: ", tc)

The given array:
 ['APple' 'oranGE' 'cHErry' 'maNGo']
Capitalize:  ['Apple' 'Orange' 'Cherry' 'Mango']
Lowercase:  ['apple' 'orange' 'cherry' 'mango']
Uppercase:  ['APPLE' 'ORANGE' 'CHERRY' 'MANGO']
Swapcase:  ['apPLE' 'ORANge' 'CheRRY' 'MAngO']
Titlecase:  ['Apple' 'Orange' 'Cherry' 'Mango']


**15. Write a NumPy program to convert a given array into
a list.**

In [27]:
a = np.array([[34,43,73],[82,22,12],[53,94,66]])
print(a)

l = a.tolist()
print("Converting array to list:\n",l)

[[34 43 73]
 [82 22 12]
 [53 94 66]]
Converting array to list:
 [[34, 43, 73], [82, 22, 12], [53, 94, 66]]


**16. Write a NumPy program to compute the sum of all
elements, sum of each column and sum of each row of a
given array.**

In [31]:
 a = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
 print(a)

 print("Sum of all elements: ",np.sum(a))
 print("Sum of each column: ",np.sum(a, axis=0))
 print("Sum of each row: ",np.sum(a, axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of all elements:  45
Sum of each column:  [12 15 18]
Sum of each row:  [ 6 15 24]


**17. Write a NumPy program to create a random 10x4
array and extract the first five rows of the array and store
them into a variable.**

In [34]:
z = np.random.random((10,4))
print(z)

five = z[:5,:]
print("Extracting only the first five rows from above array:\n",five)

[[0.14751257 0.48748108 0.97329031 0.57844911]
 [0.07486231 0.38810849 0.71792846 0.75872317]
 [0.56325886 0.44864694 0.76918768 0.45313991]
 [0.69008052 0.2793244  0.55506001 0.84996601]
 [0.92380442 0.01816583 0.97764097 0.94170977]
 [0.35222481 0.49645613 0.0604836  0.71738307]
 [0.01333419 0.2949288  0.59180744 0.94688509]
 [0.30063597 0.49267299 0.54812825 0.16507056]
 [0.4870341  0.38481519 0.099628   0.83741439]
 [0.85107585 0.52046401 0.85676906 0.63859656]]
Extracting only the first five rows from above array:
 [[0.14751257 0.48748108 0.97329031 0.57844911]
 [0.07486231 0.38810849 0.71792846 0.75872317]
 [0.56325886 0.44864694 0.76918768 0.45313991]
 [0.69008052 0.2793244  0.55506001 0.84996601]
 [0.92380442 0.01816583 0.97764097 0.94170977]]


**18. Write a NumPy program to get the unique elements of
a 1D and 2D array.**

In [37]:
one = np.array([1, 2, 3, 3, 5, 6, 6])
print("Elements of 1D array:\n",one)
print("Unique elements of 1D array:\n",np.unique(one))
print("\n")

two = np.array([[1, 2, 2],[4, 4, 6],[7, 8, 8]])
print("Elements of 2D array:\n",two)
print("Unique elements of 2D array:\n",np.unique(two))

Elements of 1D array:
 [1 2 3 3 5 6 6]
Unique elements of 1D array:
 [1 2 3 5 6]


Elements of 2D array:
 [[1 2 2]
 [4 4 6]
 [7 8 8]]
Unique elements of 2D array:
 [1 2 4 6 7 8]


**19. Write a NumPy program to get the unique elements of
an array.**

In [39]:
arr = [-10, 12.12, -0.2]
print("Elements of an array:\n",arr)
print("Unique elements of the array:\n",np.unique(arr))

Elements of an array:
 [-10, 12.12, -0.2]
Unique elements of the array:
 [-10.    -0.2   12.12]


**20. Write a NumPy program to save a given array to a text
file and load it. You have to save and load file using
numpy library.**

In [42]:
a = np.arange(16).reshape(4,4)
print(a)

np.savetxt("new.txt", a)
res = np.loadtxt("new.txt")
print("The text file:\n",res)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
The text file:
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]]
